package com.clinica.entidad;
// Generated 18-nov-2017 22:29:00 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name="cita"
    ,catalog="clinica"
)
public class Cita  implements java.io.Serializable {


     private Integer idCita;
     private Doctor doctor;
     private Paciente paciente;
     private String estado;
     private Date fecha;

    public Cita() {
    }

	
    public Cita(Doctor doctor, Paciente paciente) {
        this.doctor = doctor;
        this.paciente = paciente;
    }
    public Cita(Doctor doctor, Paciente paciente, String estado, Date fecha) {
       this.doctor = doctor;
       this.paciente = paciente;
       this.estado = estado;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cita", unique=true, nullable=false)
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctor_expediente", nullable=false)
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paciente_iddoctor", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="estado", length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


