package com.clinica.entidad;
// Generated 18-nov-2017 22:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clinica generated by hbm2java
 */
@Entity
@Table(name="clinica"
    ,catalog="clinica"
)
public class Clinica  implements java.io.Serializable {


     private int idclinica;
     private String nombre;
     private String localizacion;
     private Set<Doctor> doctors = new HashSet<Doctor>(0);

    public Clinica() {
    }

	
    public Clinica(int idclinica) {
        this.idclinica = idclinica;
    }
    public Clinica(int idclinica, String nombre, String localizacion, Set<Doctor> doctors) {
       this.idclinica = idclinica;
       this.nombre = nombre;
       this.localizacion = localizacion;
       this.doctors = doctors;
    }
   
     @Id 

    
    @Column(name="idclinica", unique=true, nullable=false)
    public int getIdclinica() {
        return this.idclinica;
    }
    
    public void setIdclinica(int idclinica) {
        this.idclinica = idclinica;
    }

    
    @Column(name="Nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="localizacion", length=45)
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clinica")
    public Set<Doctor> getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set<Doctor> doctors) {
        this.doctors = doctors;
    }




}


