package com.clinica.entidad;
// Generated 18-nov-2017 22:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="clinica"
)
public class Doctor  implements java.io.Serializable {


     private int expediente;
     private Clinica clinica;
     private String nombre;
     private String direccion;
     private String sexo;
     private Integer edad;
     private String correo;
     private Set<Cita> citas = new HashSet<Cita>(0);

    public Doctor() {
    }

	
    public Doctor(int expediente, Clinica clinica) {
        this.expediente = expediente;
        this.clinica = clinica;
    }
    public Doctor(int expediente, Clinica clinica, String nombre, String direccion, String sexo, Integer edad, String correo, Set<Cita> citas) {
       this.expediente = expediente;
       this.clinica = clinica;
       this.nombre = nombre;
       this.direccion = direccion;
       this.sexo = sexo;
       this.edad = edad;
       this.correo = correo;
       this.citas = citas;
    }
   
     @Id 

    
    @Column(name="expediente", unique=true, nullable=false)
    public int getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(int expediente) {
        this.expediente = expediente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clinica_idclinica", nullable=false)
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="sexo", length=10)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    
    @Column(name="correo", length=35)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Cita> getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set<Cita> citas) {
        this.citas = citas;
    }




}


